/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaclasscreator;

import java.io.File;


/**
 *
 * @author filip
 */
public class SecondWindow extends javax.swing.JFrame {
    File[] parametrsList;
    String parametrsPath, partPath;
    
    /**
     * Creates new form SecoundWindow
     * @param path
     */
    public SecondWindow(String path) {
     //  path = "C:\\Users\\filip\\Desktop\\Adrianowy kod\\java\\pl\\bikegame\\model\\item\\bikeparts\\parameters";
      
        System.out.println(path);
        parametrsPath = path + "\\parameters";
        partPath = path + "\\enums";
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        parametrsJList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        partJList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bike parametrs");

        parametrsJList.setModel(new javax.swing.AbstractListModel<String>() {
            File parametrsFiles = new File(parametrsPath);
            File [] parametrsList = parametrsFiles.listFiles();
            //String[] strings = file.listFiles();
            public int getSize() { return parametrsList.length; }
            public String getElementAt(int i) { return parametrsList[i].getName(); }
        });
        parametrsJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        parametrsJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                parametrsJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(parametrsJList);

        jLabel2.setText("Bike part");

        partJList.setModel(new javax.swing.AbstractListModel<String>() {
            File bikeFiles = new File(partPath);
            File[] bikeList = bikeFiles.listFiles();

            public int getSize() { return bikeList.length; }
            public String getElementAt(int i) { return bikeList[i].getName(); }
        });
        partJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(partJList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parametrsJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_parametrsJListValueChanged
        // TODO add your handling code here:
      
        boolean adjust = evt.getValueIsAdjusting();
        int selectedIndex = parametrsJList.getSelectedIndex();
        if(!adjust){
            File parametrsFiles = new File(parametrsPath);
            parametrsList = parametrsFiles.listFiles();
            String name = parametrsList[selectedIndex].getName();
            System.out.println("parametrs index: " + selectedIndex);
            System.out.println("Selected paramter class: "  + name);
            System.out.println("----------------------------");
            
            
            ParametrsWindow parametrsWindow = new ParametrsWindow(name, parametrsPath);
            parametrsWindow.setVisible(true);
           
        }
       
  
    }//GEN-LAST:event_parametrsJListValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecondWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecondWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecondWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecondWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new SecondWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> parametrsJList;
    private javax.swing.JList<String> partJList;
    // End of variables declaration//GEN-END:variables
}
